name: npm-publish

on:
  push:
    branches:
      - main # Trigger on push to the main branch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14' # Version from your package.json
          registry-url: 'https://registry.npmjs.org/' # Specify the npm registry

      - name: Prepare ignore files
        run: |
          cp .npmignore .npmignore.template
          cp .npmrc .npmrc.template
          cp .gitignore .gitignore.template
          cp lib/debug.ts lib/debug.template
          cp lib/cli.ts lib/cli.template
          cp lib/github-telegram-bot.ts lib/github-telegram-bot.template
          cp lib/ask.ts lib/ask.template
          cp lib/entities.tsx lib/entities.template
      - name: Install dependencies
        run: npm ci # Use ci for more reliable installs in CI

      - name: Run npm publish script (will fail if version exists)
        run: npm run npm-publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NEXT_PUBLIC_HASURA_GRAPHQL_URL: ${{secrets.NEXT_PUBLIC_HASURA_GRAPHQL_URL}}
          HASURA_ADMIN_SECRET: ${{secrets.HASURA_ADMIN_SECRET}}
          HASURA_JWT_SECRET: ${{secrets.HASURA_JWT_SECRET}}
          NEXT_PUBLIC_MAIN_URL: ${{secrets.NEXT_PUBLIC_MAIN_URL}}
          NEXT_PUBLIC_BASE_URL: ${{secrets.NEXT_PUBLIC_BASE_URL}}
          NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
          YANDEX_CLIENT_ID: ${{secrets.YANDEX_CLIENT_ID}}
          YANDEX_CLIENT_SECRET: ${{secrets.YANDEX_CLIENT_SECRET}}
          GITHUB_ID: ${{secrets.GITHUB_ID}}
          GITHUB_SECRET: ${{secrets.GITHUB_SECRET}}
          FACEBOOK_CLIENT_ID: ${{secrets.FACEBOOK_CLIENT_ID}}
          FACEBOOK_CLIENT_SECRET: ${{secrets.FACEBOOK_CLIENT_SECRET}}
          VK_CLIENT_ID: ${{secrets.VK_CLIENT_ID}}
          VK_CLIENT_SECRET: ${{secrets.VK_CLIENT_SECRET}}
          RESEND_API_KEY: ${{secrets.RESEND_API_KEY}}
          NODE_ENV: ${{secrets.NODE_ENV}}
          NEXT_PUBLIC_BUILD_TARGET: ${{secrets.NEXT_PUBLIC_BUILD_TARGET}}