name: test

on:
  push:
    branches:
      - main # Trigger on push to the main branch
  pull_request:
    branches:
      - main # Trigger on Pull Requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14' # Version from your package.json

      - name: Install system dependencies for node-pty
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 make

      - name: Install dependencies
        run: npm ci # Use ci for more reliable installs in CI

      - name: Run tests
        run: npm test
        env:
          JEST_LOCAL: 1
          TEST_TOKEN: ${{secrets.TEST_TOKEN}}
          NEXT_PUBLIC_HASURA_GRAPHQL_URL: ${{secrets.NEXT_PUBLIC_HASURA_GRAPHQL_URL}}
          HASURA_ADMIN_SECRET: ${{secrets.HASURA_ADMIN_SECRET}}
          HASURA_JWT_SECRET: ${{secrets.HASURA_JWT_SECRET}}
          NEXT_PUBLIC_MAIN_URL: ${{secrets.NEXT_PUBLIC_MAIN_URL}}
          NEXT_PUBLIC_BASE_URL: ${{secrets.NEXT_PUBLIC_BASE_URL}}
          NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
          YANDEX_CLIENT_ID: ${{secrets.YANDEX_CLIENT_ID}}
          YANDEX_CLIENT_SECRET: ${{secrets.YANDEX_CLIENT_SECRET}}
          GITHUB_ID: ${{secrets.GITHUB_ID}}
          GITHUB_SECRET: ${{secrets.GITHUB_SECRET}}
          FACEBOOK_CLIENT_ID: ${{secrets.FACEBOOK_CLIENT_ID}}
          FACEBOOK_CLIENT_SECRET: ${{secrets.FACEBOOK_CLIENT_SECRET}}
          VK_CLIENT_ID: ${{secrets.VK_CLIENT_ID}}
          VK_CLIENT_SECRET: ${{secrets.VK_CLIENT_SECRET}}
          RESEND_API_KEY: ${{secrets.RESEND_API_KEY}}
          NODE_ENV: ${{secrets.NODE_ENV}}
          NEXT_PUBLIC_BUILD_TARGET: ${{secrets.NEXT_PUBLIC_BUILD_TARGET}}